ignore:
  - "benchviewer/*"
  - "tests/**/*"

coverage:
  range: 60..90
  precision: 1
  status:
    project:
      default:
        threshold: 0.5%
    patch:
      default:
        threshold: 1%
codecov:
  notify:
    after_n_builds: 8
