ignore:
  - "benchviewer/*"
  - "mqt/bench/tests/*"
  - "mqt/bench/benchmark_generator.py"

coverage:
  range: 60..90
  precision: 1
  status:
    project:
      default:
        threshold: 0.5%
    patch:
      default:
        threshold: 1%
