name: Pre-Generated zip

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install MQT Predictor
        run: pip install .[test]
      - name: Run tests
        run: |
          pip install pytest
          pytest -v tests/compilation/test_pregenerated_zip.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
